Algoritmo "Celsius_to_farenheit"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
//Seção de declarações
var celsiu:real
faren:real

inicio
   //seção de comandos
   
   escreva("digite a temperatura em Farenheit", faren, ": ")
   leia(faren)

   celsiu<- (celsiu - 30) /2
   escreval("Esta temperatura em Celsius é: ", celsiu)

Fimalgoritmo