Algoritmo "Farenheit_to_celsius"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
//Seção de declarações
var celsiu:real
faren:real

inicio
   //seção de comandos
   
   escreva("digite a temperatura em Farenheit", faren, ": ")
   leia(faren)

   celsiu<- 5/9 * (faren - 32)
   escreval("Esta temperatura em Celsius é: ", celsiu)

Fimalgoritmo